import { useEffect, useMemo, useState } from "react";
import type { Diffs, FileDiff, Source } from "../types";

type TabKey = "adapter" | "spec" | "prompt";

function StatBadge({ added, removed }: { added: number; removed: number }) {
  return (
    <span className="cc-stat">
      <span className="added">+{added}</span>
      <span className="removed">−{removed}</span>
    </span>
  );
}

/** GitHub-style two-column split diff. */
function SplitDiff({ file, highlight }: { file: FileDiff; highlight: boolean }) {
  return (
    <div className={`cc-split ${highlight ? "cc-reveal" : ""}`}>
      <div className="cc-split-head">
        <span className="cc-side left">{file.before_label}</span>
        <span className="cc-side right">{file.after_label}</span>
      </div>
      <div className="cc-split-body">
        {file.rows.map((r, i) => (
          <div key={i} className={`cc-row row-${r.tag}`}>
            <span className="cc-ln">{r.leftNo ?? ""}</span>
            <span className={`cc-code left ${r.left === null ? "cc-empty" : ""}`}>
              {r.left ?? ""}
            </span>
            <span className="cc-ln">{r.rightNo ?? ""}</span>
            <span className={`cc-code right ${r.right === null ? "cc-empty" : ""}`}>
              {r.right ?? ""}
            </span>
          </div>
        ))}
      </div>
    </div>
  );
}

/** Single-file code view (no diff) with line numbers. */
function CodeView({ content, lang }: { content: string; lang: string }) {
  const lines = content.split("\n");
  return (
    <div className="cc-code-view" data-lang={lang}>
      {lines.map((line, i) => (
        <div key={i} className="cc-code-line">
          <span className="cc-ln">{i + 1}</span>
          <span className="cc-code">{line || " "}</span>
        </div>
      ))}
    </div>
  );
}

export function CodeChanges({
  source,
  diffs,
  healed,
}: {
  source: Source | null;
  diffs: Diffs | null;
  healed: boolean;
}) {
  const [tab, setTab] = useState<TabKey>("spec");

  const adapterDiff = diffs?.files.find((f) => f.key === "adapter");
  const specDiff = diffs?.files.find((f) => f.key === "spec") ?? source?.spec ?? null;
  const adapterHealed = Boolean(adapterDiff?.changed);

  // When the heal lands, pull the presenter's eye to the adapter change.
  useEffect(() => {
    if (adapterHealed) setTab("adapter");
  }, [adapterHealed]);

  const filesChanged = useMemo(() => {
    let n = 0;
    if (specDiff?.changed) n += 1;
    if (adapterHealed) n += 1;
    return n;
  }, [specDiff, adapterHealed]);

  if (!source && !diffs) return null;

  return (
    <section className="panel cc">
      <div className="cc-top">
        <h2 className="panel-title" style={{ margin: 0 }}>Code changes</h2>
        <span className="cc-summary">
          {filesChanged} file{filesChanged === 1 ? "" : "s"} changed
          {healed ? " · integration healed" : ""}
        </span>
      </div>

      <div className="cc-tabs">
        <button className={`cc-tab ${tab === "adapter" ? "active" : ""}`} onClick={() => setTab("adapter")}>
          adapter.py
          {adapterHealed && adapterDiff && (
            <StatBadge added={adapterDiff.stat.added} removed={adapterDiff.stat.removed} />
          )}
        </button>
        <button className={`cc-tab ${tab === "spec" ? "active" : ""}`} onClick={() => setTab("spec")}>
          OpenAPI spec
          {specDiff && <StatBadge added={specDiff.stat.added} removed={specDiff.stat.removed} />}
        </button>
        <button className={`cc-tab ${tab === "prompt" ? "active" : ""}`} onClick={() => setTab("prompt")}>
          durable prompt
          <span className="cc-badge-unchanged">unchanged</span>
        </button>
      </div>

      {tab === "adapter" && (
        <div className="cc-pane">
          <div className="cc-filerow">
            <code className="cc-file">{adapterDiff?.filename ?? source?.adapter_v2.filename}</code>
            {adapterHealed ? (
              <span className="cc-tag ok">v2 → v3 · regenerated by PDD</span>
            ) : (
              <span className="cc-tag idle">current v2 · regenerates to v3 on heal</span>
            )}
          </div>
          {adapterHealed && adapterDiff ? (
            <SplitDiff file={adapterDiff} highlight />
          ) : source ? (
            <CodeView content={source.adapter_v2.content} lang={source.adapter_v2.lang} />
          ) : (
            <p className="muted">Loading adapter…</p>
          )}
        </div>
      )}

      {tab === "spec" && (
        <div className="cc-pane">
          <div className="cc-filerow">
            <code className="cc-file">{specDiff?.filename}</code>
            <span className="cc-tag shift">vendor shipped a breaking change</span>
          </div>
          {specDiff ? <SplitDiff file={specDiff} highlight={false} /> : <p className="muted">Loading…</p>}
        </div>
      )}

      {tab === "prompt" && (
        <div className="cc-pane">
          <div className="cc-filerow">
            <code className="cc-file">
              {source?.prompt.filename ?? diffs?.prompt.filename}
            </code>
            <span className="cc-tag ok">intent preserved across the heal</span>
          </div>
          <CodeView content={source?.prompt.content ?? diffs?.prompt.content ?? ""} lang="text" />
        </div>
      )}
    </section>
  );
}
